# yamllint disable rule:line-length
---
name: Formula Audit

'on':
  pull_request:
    paths:
      - 'Formula/**'
  push:
    branches:
      - main
    paths:
      - 'Formula/**'
  workflow_dispatch:

jobs:
  audit:
    name: Audit Formulas
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        # yamllint disable-next-line rule:line-length
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Set up Homebrew
        id: set-up-homebrew
        # yamllint disable-next-line rule:line-length
        uses: Homebrew/actions/setup-homebrew@b2da65092292aade9599608fc29415389641b3cb

      - name: Tap repository
        run: |
          brew_repo="$(brew --repository)"
          mkdir -p "$brew_repo/Library/Taps/calebsargeant"
          ln -s "$GITHUB_WORKSPACE" \
            "$brew_repo/Library/Taps/calebsargeant/homebrew-tap"

      - name: Run brew audit
        run: |
          set -e
          for formula in Formula/*.rb; do
            if [ -f "$formula" ]; then
              formula_name=$(basename "$formula" .rb)

              # Skip example formula
              if [ "$formula_name" = "example-tool" ]; then
                echo "Skipping example formula: $formula_name"
                continue
              fi

              echo "Auditing $formula_name..."
              brew audit --strict --online "$formula_name" || exit 1
            fi
          done

      - name: Run brew style
        run: |
          set -e
          for formula in Formula/*.rb; do
            if [ -f "$formula" ]; then
              echo "Checking style for $formula..."
              brew style "$formula" || exit 1
            fi
          done
