# yamllint disable rule:line-length
---
name: Formula Tests

'on':
  pull_request:
    paths:
      - 'Formula/**'
  push:
    branches:
      - main
    paths:
      - 'Formula/**'
  workflow_dispatch:

jobs:
  test:
    name: Test Formulas
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, macos-14]
      fail-fast: false

    steps:
      - name: Checkout repository
        # yamllint disable-next-line rule:line-length
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Set up Homebrew
        id: set-up-homebrew
        # yamllint disable-next-line rule:line-length
        uses: Homebrew/actions/setup-homebrew@b2da65092292aade9599608fc29415389641b3cb

      - name: Tap repository
        run: |
          brew_repo="$(brew --repository)"
          mkdir -p "$brew_repo/Library/Taps/calebsargeant"
          ln -s "$GITHUB_WORKSPACE" \
            "$brew_repo/Library/Taps/calebsargeant/homebrew-tap"

      - name: Install and test formulas
        run: |
          set -e
          for formula in Formula/*.rb; do
            if [ -f "$formula" ]; then
              formula_name=$(basename "$formula" .rb)

              # Skip example formula
              if [ "$formula_name" = "example-tool" ]; then
                echo "Skipping example formula: $formula_name"
                continue
              fi

              echo "Testing $formula_name..."

              # Install formula
              brew install --build-from-source "$formula_name" || {
                echo "Failed to install $formula_name"
                exit 1
              }

              # Run formula tests
              brew test "$formula_name" || {
                echo "Tests failed for $formula_name"
                exit 1
              }

              # Uninstall to clean up
              brew uninstall "$formula_name"
            fi
          done

      - name: Summary
        if: always()
        run: |
          echo "Formula testing completed"
          brew --version
